module.exports = {
    moduleFileExtensions: [ 'ts', 'js' ],
    transform: {
        '.*\\.(js)$': 'babel-jest',
        '.*\\.(ts)$': 'ts-jest',
        '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2|svg)$': 'jest-transform-stub',
    },
    transformIgnorePatterns: [],
    testEnvironment: 'jsdom',
    testPathIgnorePatterns: [ '/plugins/' ],
    clearMocks: true,
    collectCoverage: true,
    collectCoverageFrom: [
        'src/app/**/*.ts',
        '!**/*.module.ts',
        '!src/app/secure-browser-storage/**/*.*',
        '!src/app/models/**/*.*',
        '!{isolated-storage}/**.*',
        '!{test-utils}/**.*',
        '!{environments}/**.*',
        '!**/node_modules/**',
    ],
    coverageDirectory: 'coverage',
    coveragePathIgnorePatterns: [ '/node_modules/' ],
    errorOnDeprecated: true,
    setupFiles: [ '<rootDir>/jest.setup.js' ],
    watchman: false,
    verbose: true,
    expand: true,
}
